### ISSUE TITLE
Please provide a couple of example usages

### ISSUE THREAD

**Issue by ajkswamy** [shimazaki/AdaptiveKDE#5]
Dear developers of AdaptiveKDE method,

I am trying to use this package for estimating the temporal firing rate profile from spike trains of several trials. I had a look a the function "ssvkernel" and I am having trouble understanding the input parameters of this function. The argument "x" says it requires "The one-dimensional samples drawn from the underlying density". I am not able to figure out how to transform information in the trial spike trains of my data before supplying it to "x". Could you provide an example use case, preferably, the code used to generate Fig. 4(b) or (c) of [the reference](http://dx.doi.org/10.1007/s10827-009-0180-4)?

Thank you.

Sincerely
Ajay

**Comment by cooperlab** [comment]
Ajay - This question is best directed to the author of the paper. 

The ssvkernel function estimates the smoothed probability density for a 1D vector of measurements. I think of it as a denoised histogram. What I think the figure from Hideaki's paper shows is that if you apply this function to a vector containing the times where spikes occur (a "spike sequence") you will get a smoothed density of when these spikes are likely to occur.
