### ISSUE TITLE
Code breaks on sskernel line 182

### ISSUE THREAD

**Issue by wetarded1** [shimazaki/AdaptiveKDE#6]
The code needs to cast from a float to an int when making the call to np.ceil().  Right now it wont run unless the code is normalized to integer values.

**Comment by chiarabellenghi** [comment]
Same for ssvkernel L79

> File ~/.local/share/virtualenvs/icecube_stacking_analysis-MXDoC4ds/lib/python3.10/site-packages/adaptivekde/ssvkernel.py:79, in ssvkernel(x, tin, M, nbs, WinFunc)
     77 dx = np.sort(np.diff(np.sort(x)))
     78 dt_samp = dx[np.nonzero(dx)][0]
---> 79 tin = np.linspace(np.min(x), np.max(x), min(np.ceil(T / dt_samp), 1e3))
     80 t = tin
     81 x_ab = x[(x >= min(tin)) & (x <= max(tin))]

> File <__array_function__ internals>:180, in linspace(*args, **kwargs)

> File ~/.local/share/virtualenvs/icecube_stacking_analysis-MXDoC4ds/lib/python3.10/site-packages/numpy/core/function_base.py:120, in linspace(start, stop, num, endpoint, retstep, dtype, axis)
     23 @array_function_dispatch(_linspace_dispatcher)
     24 def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
     25              axis=0):
     26     """
     27     Return evenly spaced numbers over a specified interval.
     28 
   (...)
    118 
    119     """
--> 120     num = operator.index(num)
    121     if num < 0:
    122         raise ValueError("Number of samples, %s, must be non-negative." % num)

> TypeError: 'numpy.float64' object cannot be interpreted as an integer

​

**Comment by shimazaki** [comment]
These issues were corrected by lqkhoo.
